files:
  - source: /i18n/en/strings.js
    translation: /i18n/%two_letters_code%/strings.js
  - source: /android/app/src/main/res/values/strings.xml
    translation: /android/app/src/main/res/values-%two_letters_code%/strings.xml
