name: Discord Bot Delivery

on:
  push:
    branches:
      - main
    paths:
      - discord-bot/**

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: DRSchlaubi/heroku-deploy@patch-1
        with:
          api_key: ${{secrets.HEROKU_API_KEY}}
          app_name: "desolate-earth-51306"
          email: ${{secrets.HEROKU_EMAIL}}
          dockerfile_path: "discord-bot"
